### ISSUE TITLE
Document hub state packaging design

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-utils#5]
Open instruction on superhub.io. Complete installation steps. Not getting hub state extension

- [x] Document `hub state` packaging design 
- [x] ~~Review with development team revisited hub extensions packaging design~~
- [x] ~~Implement~~
- [x] ~~Update `superhub.io` documentation~~

**Comment by TheRealSpaceShip** [comment]
I don't see a point to distribute `hub state` as a separate tool. Packaging of `hub state` is done in the scope of https://github.com/agilestacks/hub-state/issues/7. `hub state` will be delivered in `hub extensions` package so I see no needs to update `superhub.io`. In this case, there are two actions that should be done:

- [x] Create the first release of `hub state` extension
- [ ] https://github.com/agilestacks/hub-extensions/issues/19

**Comment by TheRealSpaceShip** [comment]
Documented in hub state cli [readme](https://github.com/agilestacks/hub-state/blob/master/cli/README.md#release-process)
