### ISSUE TITLE
Authorise calls to hub-state function

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub-utils#9]
Currently, we deploy the hub state as an anonymous function. We need to protect it using the access token.
In the scope of this task:
- [ ] rework the way how the function is deployed - allow only authorized calls
- [x] rework the way how the function is used - before function invocation retrieve the access token through `gcloud`

**Comment by akranga** [comment]
Closing as per [comment](https://github.com/epam/hub-extensions/issues/31#issuecomment-1681277403)
